---

- name: install pre-requirements
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    #    - name: Message
    #  debug:
    #    msg: "install prerequirements"

    # todo: SE linux /etc/selinux/config SELINUX=permissive


    - name: Ensure prerequirements are installed
      dnf:
        name: "{{ item }}"
        state: present
        update_cache: yes
          #allow_downgrade: yes
      loop:
        - motif
        - motif-devel
        - ksh
          #- libnscl

    - name: set SElinux to permissive mode
      ansible.builtin.lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: SELINUX=permissive

- name: install SRAdmin
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: create sradmin directory
      ansible.builtin.file:
        path: /sw/SPECTRUM/SRAdmin
        state: directory
        mode: '0755'

    - name: copy sradmin.exe2yy
      copy:
        src: "{{ dist_dir }}/sdic/linux/sradmin.exe"
        dest: /sw/SPECTRUM/SRAdmin
        mode: '0744'

    - name: prepare rc2.d
      copy:
        src: "{{ dist_dir }}/sdic/linux/sradmin.rc2"
        dest: /etc/init.d/sradmin

    - name: chmod
      ansible.builtin.file:
        path: /etc/init.d/sradmin
        mode: '0500'

    - name: enable and start sradmin
      service:
        name: sradmin
        enabled: yes

    - name: enable and start sradmin
      service:
        name: sradmin
        state: started

- name: prepare hostargs
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: create install hostargs file
      ansible.builtin.lineinfile:
        path: "/tmp/{{ ansible_hostname }}.hostargs"
        line: remote_host={{ ansible_hostname }}
        create: yes

    - name: add landscape to hostargs
      ansible.builtin.lineinfile:
        path: "/tmp/{{ ansible_hostname }}.hostargs"
        line: l_handle={{ lh }}

    - name: add install directory to hostargs
      ansible.builtin.lineinfile:
        path: "/tmp/{{ ansible_hostname }}.hostargs"
        line: install_dir={{ install_dir }}

    - name: add install media path
      ansible.builtin.lineinfile:
        path: "/tmp/{{ ansible_hostname }}.hostargs"
        line: vcd_path={{ install_dir }}

    - name: add install ss
      ansible.builtin.lineinfile:
        path: "/tmp/{{ ansible_hostname }}.hostargs"
        line: ss_install=yes

    - name: add install oneclick
      ansible.builtin.lineinfile:
        path: "/tmp/{{ ansible_hostname }}.hostargs"
        line: oc_install=yes

    - name: copy hostargs to localhost
      ansible.builtin.fetch:
        src: /tmp/{{ ansible_hostname }}.hostargs
        dest: ./
        flat: yes

    - name: create install password file
      ansible.builtin.lineinfile:
        path: "/tmp/{{ ansible_hostname }}.pw"
        line: "{{ ansible_hostname }} {{ ansible_user }} {{ ansible_ssh_pass }}"
        create: yes

    - name: copy password file to localhost
      ansible.builtin.fetch:
        src: /tmp/{{ ansible_hostname }}.pw
        dest: ./
        flat: yes

    - name: start spectrum silent installation
      ansible.builtin.command: "{{ dist_dir }}/sdic/sdiclinux.exe -h ./{{ ansible_hostname }}.hostargs -p ./{{ ansible_hostname }}.pw -test"
      delegate_to: 127.0.0.1